export const SCHOOL = {
  id: "sch-001",
  name: "Delhi Public School, Vijayawada",
  username: "dps-vijayawada",
  board: "CBSE",
  plan: "Growth",
  planExpiry: "2026-12-31",
  daysLeft: 244,
  city: "Vijayawada",
  state: "Andhra Pradesh",
  totalStudents: 486,
  totalTeachers: 24,
  totalClasses: 12,
  studentLimit: 500,
  attendanceToday: 86.6,
  presentToday: 421,
  absentToday: 42,
  lateToday: 18,
  excusedToday: 5,
  activeAssignments: 8,
  overdueAssignments: 1,
  quizzesThisWeek: 1243,
  openDoubts: 4,
  gamesPlayedToday: 87,
  avgScoreThisWeek: 74.2,
  aiQuizzesMonth: 234,
  aiCostInr: 1033,
  atRiskStudents: 23,
};

export const ADMIN = {
  id: "usr-001",
  name: "Mrs. Kavitha Reddy",
  email: "kavitha@dps.edu",
  phone: "9876540001",
  initials: "KR",
  color: "#FF6B35",
  role: "SCHOOL",
};

export const CLASSES = [
  {
    id: "cls-001",
    name: "Grade 6",
    section: "A",
    grade: 6,
    students: 38,
    subjects: 5,
    avgScore: 71,
    attendance: 94,
    classTeacher: "Mrs. P. Mehta",
    classTeacherId: "tch-003",
    color: "#3B82F6",
    activeAssignments: 4,
    topStudent: "Kavya Reddy",
    topXp: 2340,
    quizzesWeek: 87,
    gamesWeek: 23,
    boardExam: false,
    atRisk: 3,
  },
  {
    id: "cls-002",
    name: "Grade 6",
    section: "B",
    grade: 6,
    students: 36,
    subjects: 5,
    avgScore: 68,
    attendance: 89,
    classTeacher: "Mr. A. Kumar",
    classTeacherId: "tch-004",
    color: "#3B82F6",
    activeAssignments: 3,
    topStudent: "Rohit Verma",
    topXp: 2180,
    quizzesWeek: 72,
    gamesWeek: 18,
    boardExam: false,
    atRisk: 4,
  },
  {
    id: "cls-003",
    name: "Grade 7",
    section: "A",
    grade: 7,
    students: 42,
    subjects: 5,
    avgScore: 74,
    attendance: 91,
    classTeacher: "Mrs. S. Kumari",
    classTeacherId: "tch-001",
    color: "#8B5CF6",
    activeAssignments: 5,
    topStudent: "Sneha Patel",
    topXp: 3980,
    quizzesWeek: 103,
    gamesWeek: 31,
    boardExam: false,
    atRisk: 2,
  },
  {
    id: "cls-004",
    name: "Grade 7",
    section: "B",
    grade: 7,
    students: 40,
    subjects: 5,
    avgScore: 78,
    attendance: 93,
    classTeacher: "Mr. R. Sharma",
    classTeacherId: "tch-002",
    color: "#8B5CF6",
    activeAssignments: 4,
    topStudent: "Aryan Singh",
    topXp: 3720,
    quizzesWeek: 96,
    gamesWeek: 28,
    boardExam: false,
    atRisk: 1,
  },
  {
    id: "cls-005",
    name: "Grade 8",
    section: "A",
    grade: 8,
    students: 40,
    subjects: 5,
    avgScore: 82,
    attendance: 95,
    classTeacher: "Mrs. S. Kumari",
    classTeacherId: "tch-001",
    color: "#FF6B35",
    activeAssignments: 8,
    topStudent: "Priya Nair",
    topXp: 4820,
    quizzesWeek: 124,
    gamesWeek: 41,
    boardExam: false,
    atRisk: 1,
  },
  {
    id: "cls-006",
    name: "Grade 8",
    section: "B",
    grade: 8,
    students: 38,
    subjects: 5,
    avgScore: 74,
    attendance: 88,
    classTeacher: "Mr. A. Kumar",
    classTeacherId: "tch-004",
    color: "#FF6B35",
    activeAssignments: 5,
    topStudent: "Meena Iyer",
    topXp: 3140,
    quizzesWeek: 98,
    gamesWeek: 29,
    boardExam: false,
    atRisk: 3,
  },
  {
    id: "cls-007",
    name: "Grade 9",
    section: "A",
    grade: 9,
    students: 44,
    subjects: 6,
    avgScore: 62,
    attendance: 87,
    classTeacher: "Mrs. P. Mehta",
    classTeacherId: "tch-003",
    color: "#10B981",
    activeAssignments: 3,
    topStudent: "Vikram Rao",
    topXp: 2840,
    quizzesWeek: 78,
    gamesWeek: 15,
    boardExam: false,
    atRisk: 6,
  },
  {
    id: "cls-008",
    name: "Grade 9",
    section: "B",
    grade: 9,
    students: 42,
    subjects: 6,
    avgScore: 65,
    attendance: 86,
    classTeacher: "Mr. R. Sharma",
    classTeacherId: "tch-002",
    color: "#10B981",
    activeAssignments: 3,
    topStudent: "Divya K",
    topXp: 2650,
    quizzesWeek: 82,
    gamesWeek: 17,
    boardExam: false,
    atRisk: 5,
  },
  {
    id: "cls-009",
    name: "Grade 10",
    section: "A",
    grade: 10,
    students: 46,
    subjects: 6,
    avgScore: 58,
    attendance: 82,
    classTeacher: "Mrs. S. Nair",
    classTeacherId: "tch-005",
    color: "#F59E0B",
    activeAssignments: 2,
    topStudent: "Sanjay M",
    topXp: 2120,
    quizzesWeek: 64,
    gamesWeek: 8,
    boardExam: true,
    atRisk: 8,
  },
  {
    id: "cls-010",
    name: "Grade 10",
    section: "B",
    grade: 10,
    students: 44,
    subjects: 6,
    avgScore: 55,
    attendance: 79,
    classTeacher: "Mrs. S. Nair",
    classTeacherId: "tch-005",
    color: "#F59E0B",
    activeAssignments: 2,
    topStudent: "Asha P",
    topXp: 1980,
    quizzesWeek: 58,
    gamesWeek: 6,
    boardExam: true,
    atRisk: 9,
  },
  {
    id: "cls-011",
    name: "Grade 11",
    section: "A",
    grade: 11,
    students: 40,
    subjects: 4,
    avgScore: 69,
    attendance: 91,
    classTeacher: "Mrs. P. Mehta",
    classTeacherId: "tch-003",
    color: "#EC4899",
    activeAssignments: 3,
    topStudent: "Karthik N",
    topXp: 3240,
    quizzesWeek: 74,
    gamesWeek: 12,
    boardExam: false,
    atRisk: 2,
  },
  {
    id: "cls-012",
    name: "Grade 12",
    section: "A",
    grade: 12,
    students: 46,
    subjects: 4,
    avgScore: 72,
    attendance: 94,
    classTeacher: "Mrs. S. Kumari",
    classTeacherId: "tch-001",
    color: "#0EA5E9",
    activeAssignments: 4,
    topStudent: "Deepa R",
    topXp: 3680,
    quizzesWeek: 88,
    gamesWeek: 9,
    boardExam: true,
    atRisk: 2,
  },
];

export const TEACHERS = [
  {
    id: "tch-001",
    name: "Mrs. S. Kumari",
    email: "s.kumari@dps.edu",
    phone: "9876543210",
    initials: "SK",
    color: "#FF6B35",
    subjects: ["Mathematics", "Science"],
    classes: ["Grade 7-A", "Grade 8-A", "Grade 12-A"],
    classIds: ["cls-003", "cls-005", "cls-012"],
    quizzes: 47,
    students: 156,
    avgScore: 79,
    lastActive: "Today",
    isActive: true,
    designation: "Senior Teacher",
    joinedDate: "2019-06-01",
  },
  {
    id: "tch-002",
    name: "Mr. R. Sharma",
    email: "r.sharma@dps.edu",
    phone: "9876543211",
    initials: "RS",
    color: "#3B82F6",
    subjects: ["Science", "SST"],
    classes: ["Grade 7-A", "Grade 7-B", "Grade 9-B"],
    classIds: ["cls-003", "cls-004", "cls-008"],
    quizzes: 38,
    students: 143,
    avgScore: 76,
    lastActive: "2h ago",
    isActive: true,
    designation: "Teacher",
    joinedDate: "2020-07-15",
  },
  {
    id: "tch-003",
    name: "Mrs. P. Mehta",
    email: "p.mehta@dps.edu",
    phone: "9876543212",
    initials: "PM",
    color: "#8B5CF6",
    subjects: ["English", "Hindi"],
    classes: ["Grade 6-A", "Grade 6-B", "Grade 9-A", "Grade 11-A"],
    classIds: ["cls-001", "cls-002", "cls-007", "cls-011"],
    quizzes: 29,
    students: 164,
    avgScore: 74,
    lastActive: "Today",
    isActive: true,
    designation: "Senior Teacher",
    joinedDate: "2018-04-10",
  },
  {
    id: "tch-004",
    name: "Mr. A. Kumar",
    email: "a.kumar@dps.edu",
    phone: "9876543213",
    initials: "AK",
    color: "#10B981",
    subjects: ["Mathematics"],
    classes: ["Grade 6-B", "Grade 8-B"],
    classIds: ["cls-002", "cls-006"],
    quizzes: 24,
    students: 74,
    avgScore: 71,
    lastActive: "Yesterday",
    isActive: true,
    designation: "Teacher",
    joinedDate: "2021-06-01",
  },
  {
    id: "tch-005",
    name: "Mrs. S. Nair",
    email: "s.nair@dps.edu",
    phone: "9876543214",
    initials: "SN",
    color: "#F59E0B",
    subjects: ["SST", "History", "Geography"],
    classes: ["Grade 9-A", "Grade 9-B", "Grade 10-A", "Grade 10-B"],
    classIds: ["cls-007", "cls-008", "cls-009", "cls-010"],
    quizzes: 18,
    students: 176,
    avgScore: 69,
    lastActive: "3 days ago",
    isActive: true,
    designation: "Teacher",
    joinedDate: "2022-07-01",
  },
];

export const STUDENTS = [
  {
    id: "std-001",
    name: "Priya Nair",
    email: "priya.n@dps.edu",
    initials: "PN",
    color: "#EC4899",
    classId: "cls-005",
    className: "Grade 8-A",
    recordId: "rec-001",
    xp: 4820,
    level: 9,
    levelName: "Champion",
    streak: 21,
    avgScore: 91,
    attendance: 98,
    status: "Active",
    rollNo: "8A-01",
    strongTopic: "Fractions",
    weakTopic: "Algebra",
    gamesPlayed: 15,
    gamesWon: 12,
    rank: 1,
    badges: 7,
    lastActive: "Today",
  },
  {
    id: "std-002",
    name: "Rahul Mehta",
    email: "rahul.m@dps.edu",
    initials: "RM",
    color: "#3B82F6",
    classId: "cls-005",
    className: "Grade 8-A",
    recordId: "rec-002",
    xp: 4210,
    level: 8,
    levelName: "Scholar",
    streak: 18,
    avgScore: 87,
    attendance: 96,
    status: "Active",
    rollNo: "8A-02",
    strongTopic: "Integers",
    weakTopic: "Mensuration",
    gamesPlayed: 13,
    gamesWon: 10,
    rank: 2,
    badges: 5,
    lastActive: "Today",
  },
  {
    id: "std-003",
    name: "Arjun Sharma",
    email: "arjun.s@dps.edu",
    initials: "AS",
    color: "#FF6B35",
    classId: "cls-005",
    className: "Grade 8-A",
    recordId: "rec-003",
    xp: 3240,
    level: 7,
    levelName: "Scholar",
    streak: 14,
    avgScore: 80,
    attendance: 94,
    status: "Active",
    rollNo: "8A-03",
    strongTopic: "Fractions",
    weakTopic: "Algebra",
    gamesPlayed: 8,
    gamesWon: 6,
    rank: 4,
    badges: 3,
    lastActive: "2h ago",
  },
  {
    id: "std-004",
    name: "Sneha Patel",
    email: "sneha.p@dps.edu",
    initials: "SP",
    color: "#10B981",
    classId: "cls-003",
    className: "Grade 7-A",
    recordId: "rec-004",
    xp: 3980,
    level: 8,
    levelName: "Scholar",
    streak: 12,
    avgScore: 85,
    attendance: 92,
    status: "Active",
    rollNo: "7A-01",
    strongTopic: "Data Handling",
    weakTopic: "Fractions",
    gamesPlayed: 11,
    gamesWon: 8,
    rank: 3,
    badges: 4,
    lastActive: "Today",
  },
  {
    id: "std-005",
    name: "Dev Kumar",
    email: "dev.k@dps.edu",
    initials: "DK",
    color: "#8B5CF6",
    classId: "cls-005",
    className: "Grade 8-A",
    recordId: "rec-005",
    xp: 3100,
    level: 7,
    levelName: "Scholar",
    streak: 9,
    avgScore: 74,
    attendance: 88,
    status: "Active",
    rollNo: "8A-04",
    strongTopic: "Integers",
    weakTopic: "Exponents",
    gamesPlayed: 9,
    gamesWon: 5,
    rank: 5,
    badges: 2,
    lastActive: "3h ago",
  },
  {
    id: "std-006",
    name: "Kavya Reddy",
    email: "kavya.r@dps.edu",
    initials: "KR",
    color: "#F59E0B",
    classId: "cls-001",
    className: "Grade 6-A",
    recordId: "rec-006",
    xp: 2340,
    level: 5,
    levelName: "Learner",
    streak: 7,
    avgScore: 72,
    attendance: 91,
    status: "Active",
    rollNo: "6A-01",
    strongTopic: "Fractions",
    weakTopic: "Algebra",
    gamesPlayed: 5,
    gamesWon: 3,
    rank: 7,
    badges: 2,
    lastActive: "Yesterday",
  },
  {
    id: "std-007",
    name: "Anita Singh",
    email: "anita.s@dps.edu",
    initials: "AN",
    color: "#EF4444",
    classId: "cls-003",
    className: "Grade 7-A",
    recordId: "rec-007",
    xp: 890,
    level: 3,
    levelName: "Learner",
    streak: 2,
    avgScore: 38,
    attendance: 71,
    status: "At-Risk",
    rollNo: "7A-15",
    strongTopic: "Basic Operations",
    weakTopic: "Fractions",
    gamesPlayed: 2,
    gamesWon: 0,
    rank: 38,
    badges: 1,
    lastActive: "4 days ago",
  },
  {
    id: "std-008",
    name: "Ravi Kumar",
    email: "ravi.k@dps.edu",
    initials: "RK",
    color: "#EF4444",
    classId: "cls-002",
    className: "Grade 6-B",
    recordId: "rec-008",
    xp: 540,
    level: 2,
    levelName: "Learner",
    streak: 0,
    avgScore: 32,
    attendance: 68,
    status: "At-Risk",
    rollNo: "6B-11",
    strongTopic: "English",
    weakTopic: "Mathematics",
    gamesPlayed: 1,
    gamesWon: 0,
    rank: 36,
    badges: 0,
    lastActive: "5 days ago",
  },
  {
    id: "std-009",
    name: "Meena Iyer",
    email: "meena.i@dps.edu",
    initials: "MI",
    color: "#0EA5E9",
    classId: "cls-006",
    className: "Grade 8-B",
    recordId: "rec-009",
    xp: 3140,
    level: 7,
    levelName: "Scholar",
    streak: 6,
    avgScore: 76,
    attendance: 90,
    status: "Active",
    rollNo: "8B-01",
    strongTopic: "Mensuration",
    weakTopic: "Exponents",
    gamesPlayed: 9,
    gamesWon: 5,
    rank: 3,
    badges: 3,
    lastActive: "Today",
  },
  {
    id: "std-010",
    name: "Karthik N",
    email: "karthik.n@dps.edu",
    initials: "KN",
    color: "#6366F1",
    classId: "cls-011",
    className: "Grade 11-A",
    recordId: "rec-010",
    xp: 3240,
    level: 7,
    levelName: "Scholar",
    streak: 11,
    avgScore: 69,
    attendance: 91,
    status: "Active",
    rollNo: "11A-01",
    strongTopic: "Physics",
    weakTopic: "Chemistry",
    gamesPlayed: 6,
    gamesWon: 3,
    rank: 4,
    badges: 2,
    lastActive: "Today",
  },
];

export const SUBJECTS = [
  {
    id: "sub-001",
    name: "Mathematics",
    isGlobal: true,
    classCount: 8,
    color: "#3B82F6",
    icon: "∑",
  },
  {
    id: "sub-002",
    name: "Science",
    isGlobal: true,
    classCount: 8,
    color: "#10B981",
    icon: "⚗",
  },
  {
    id: "sub-003",
    name: "English",
    isGlobal: true,
    classCount: 12,
    color: "#8B5CF6",
    icon: "A",
  },
  {
    id: "sub-004",
    name: "Hindi",
    isGlobal: true,
    classCount: 12,
    color: "#F59E0B",
    icon: "ह",
  },
  {
    id: "sub-005",
    name: "Social Studies",
    isGlobal: true,
    classCount: 6,
    color: "#EC4899",
    icon: "⚔",
  },
  {
    id: "sub-006",
    name: "Vedic Mathematics",
    isGlobal: false,
    classCount: 2,
    color: "#FF6B35",
    icon: "✦",
  },
  {
    id: "sub-007",
    name: "Computer Science",
    isGlobal: false,
    classCount: 4,
    color: "#0EA5E9",
    icon: "⌨",
  },
];

export const ASSIGNMENTS = [
  {
    id: "asgn-001",
    title: "Fractions Practice Set",
    classId: "cls-005",
    className: "Grade 8-A",
    subjectId: "sub-001",
    subject: "Mathematics",
    teacherId: "tch-001",
    teacher: "Mrs. S. Kumari",
    mode: "HOMEWORK",
    status: "ACTIVE",
    topic: "Fractions",
    difficulty: "MEDIUM",
    questions: 15,
    timeMinutes: 20,
    submitted: 28,
    total: 40,
    avgScore: 79,
    dueDate: "2026-03-22T18:00:00",
    isOverdue: false,
    isUrgent: true,
    source: "PREBUILT",
    xpReward: 36,
  },
  {
    id: "asgn-002",
    title: "Integers Speed Blitz",
    classId: "cls-003",
    className: "Grade 7-A",
    subjectId: "sub-001",
    subject: "Mathematics",
    teacherId: "tch-001",
    teacher: "Mrs. S. Kumari",
    mode: "GAME",
    status: "ACTIVE",
    topic: "Integers",
    difficulty: "MEDIUM",
    questions: 10,
    timeMinutes: 8,
    submitted: 31,
    total: 42,
    avgScore: 74,
    dueDate: "2026-03-23T09:00:00",
    isOverdue: false,
    isUrgent: false,
    source: "PREBUILT",
    xpReward: 50,
  },
  {
    id: "asgn-003",
    title: "Photosynthesis Quiz",
    classId: "cls-002",
    className: "Grade 6-B",
    subjectId: "sub-002",
    subject: "Science",
    teacherId: "tch-002",
    teacher: "Mr. R. Sharma",
    mode: "HOMEWORK",
    status: "ACTIVE",
    topic: "Nutrition in Plants",
    difficulty: "EASY",
    questions: 10,
    timeMinutes: 15,
    submitted: 8,
    total: 36,
    avgScore: 68,
    dueDate: "2026-03-25T09:00:00",
    isOverdue: false,
    isUrgent: false,
    source: "PREBUILT",
    xpReward: 24,
  },
  {
    id: "asgn-004",
    title: "Monthly Science Olympiad",
    classId: "cls-005",
    className: "All Classes",
    subjectId: "sub-002",
    subject: "Science",
    teacherId: "tch-002",
    teacher: "Mr. R. Sharma",
    mode: "COMPETITION",
    status: "ACTIVE",
    topic: "Mixed",
    difficulty: "HARD",
    questions: 30,
    timeMinutes: 45,
    submitted: 156,
    total: 486,
    avgScore: 72,
    dueDate: "2026-03-29T23:59:00",
    isOverdue: false,
    isUrgent: false,
    source: "PREBUILT",
    xpReward: 100,
  },
  {
    id: "asgn-005",
    title: "Light and Shadows",
    classId: "cls-003",
    className: "Grade 7-A",
    subjectId: "sub-002",
    subject: "Science",
    teacherId: "tch-002",
    teacher: "Mr. R. Sharma",
    mode: "HOMEWORK",
    status: "ACTIVE",
    topic: "Light",
    difficulty: "EASY",
    questions: 10,
    timeMinutes: 15,
    submitted: 30,
    total: 42,
    avgScore: 71,
    dueDate: "2026-03-20T18:00:00",
    isOverdue: true,
    isUrgent: true,
    source: "PREBUILT",
    xpReward: 24,
  },
];

export const ANNOUNCEMENTS = [
  {
    id: "ann-001",
    title: "Annual Day — April 15, 2026",
    content:
      "Annual Day celebrations on April 15. All students attend in uniform by 8:30 AM. Parents cordially invited.",
    audience: "ALL",
    isPinned: true,
    targetClassId: null,
    targetClassName: null,
    createdAt: "2026-03-15",
    expiresAt: "2026-04-16",
    createdBy: "Mrs. Kavitha Reddy",
  },
  {
    id: "ann-002",
    title: "Unit Test Schedule — March 25–29",
    content:
      "Unit tests for Classes 6-10 from March 25 to 29. Timetable shared in each class.",
    audience: "STUDENTS",
    isPinned: false,
    targetClassId: null,
    targetClassName: null,
    createdAt: "2026-03-20",
    expiresAt: null,
    createdBy: "Mrs. Kavitha Reddy",
  },
  {
    id: "ann-003",
    title: "Parent-Teacher Meeting — April 5",
    content:
      "PTM for all classes on April 5 from 9 AM to 1 PM. Parents requested to attend.",
    audience: "ALL",
    isPinned: false,
    targetClassId: null,
    targetClassName: null,
    createdAt: "2026-03-18",
    expiresAt: "2026-04-05",
    createdBy: "Mrs. Kavitha Reddy",
  },
  {
    id: "ann-004",
    title: "Grade 8-A Board Prep Extra Classes",
    content:
      "Extra preparation classes every Saturday from 9 AM to 12 PM starting March 29.",
    audience: "STUDENTS",
    isPinned: false,
    targetClassId: "cls-005",
    targetClassName: "Grade 8-A",
    createdAt: "2026-03-21",
    expiresAt: null,
    createdBy: "Mrs. Kavitha Reddy",
  },
];

export const LEADERBOARD = [
  {
    rank: 1,
    studentId: "std-001",
    name: "Priya Nair",
    initials: "PN",
    color: "#EC4899",
    className: "Grade 8-A",
    xp: 4820,
    score: 91,
    games: 15,
    wins: 12,
    accuracy: 91,
    streak: 21,
    change: 0,
  },
  {
    rank: 2,
    studentId: "std-002",
    name: "Rahul Mehta",
    initials: "RM",
    color: "#3B82F6",
    className: "Grade 8-A",
    xp: 4210,
    score: 87,
    games: 13,
    wins: 10,
    accuracy: 87,
    streak: 18,
    change: 1,
  },
  {
    rank: 3,
    studentId: "std-004",
    name: "Sneha Patel",
    initials: "SP",
    color: "#10B981",
    className: "Grade 7-A",
    xp: 3980,
    score: 85,
    games: 11,
    wins: 8,
    accuracy: 85,
    streak: 12,
    change: -1,
  },
  {
    rank: 4,
    studentId: "std-003",
    name: "Arjun Sharma",
    initials: "AS",
    color: "#FF6B35",
    className: "Grade 8-A",
    xp: 3240,
    score: 80,
    games: 8,
    wins: 6,
    accuracy: 80,
    streak: 14,
    change: 2,
  },
  {
    rank: 5,
    studentId: "std-009",
    name: "Meena Iyer",
    initials: "MI",
    color: "#0EA5E9",
    className: "Grade 8-B",
    xp: 3140,
    score: 76,
    games: 9,
    wins: 5,
    accuracy: 76,
    streak: 6,
    change: -1,
  },
  {
    rank: 6,
    studentId: "std-005",
    name: "Dev Kumar",
    initials: "DK",
    color: "#8B5CF6",
    className: "Grade 8-B",
    xp: 3100,
    score: 74,
    games: 9,
    wins: 5,
    accuracy: 74,
    streak: 9,
    change: 0,
  },
  {
    rank: 7,
    studentId: "std-006",
    name: "Kavya Reddy",
    initials: "KR",
    color: "#F59E0B",
    className: "Grade 6-A",
    xp: 2340,
    score: 72,
    games: 5,
    wins: 3,
    accuracy: 72,
    streak: 7,
    change: 0,
  },
];

export const DOUBTS = [
  {
    id: "dbt-001",
    studentId: "std-003",
    studentName: "Arjun Sharma",
    studentInitials: "AS",
    studentColor: "#FF6B35",
    className: "Grade 8-A",
    teacherId: "tch-001",
    teacherName: "Mrs. S. Kumari",
    subject: "Mathematics",
    topic: "Fractions",
    content:
      "How do I multiply mixed fractions? When do I convert to improper fractions first?",
    answer: null,
    status: "OPEN",
    createdAt: "2026-03-22T10:30:00",
    answeredAt: null,
  },
  {
    id: "dbt-002",
    studentId: "std-006",
    studentName: "Kavya Reddy",
    studentInitials: "KR",
    studentColor: "#F59E0B",
    className: "Grade 6-A",
    teacherId: "tch-001",
    teacherName: "Mrs. S. Kumari",
    subject: "Mathematics",
    topic: "LCM and HCF",
    content: "What is LCM and when do I use it vs HCF?",
    answer: null,
    status: "OPEN",
    createdAt: "2026-03-22T08:15:00",
    answeredAt: null,
  },
  {
    id: "dbt-003",
    studentId: "std-005",
    studentName: "Dev Kumar",
    studentInitials: "DK",
    studentColor: "#8B5CF6",
    className: "Grade 8-A",
    teacherId: "tch-001",
    teacherName: "Mrs. S. Kumari",
    subject: "Mathematics",
    topic: "HCF",
    content: "What is the difference between HCF and GCD?",
    answer:
      "HCF and GCD are the same concept — different names. HCF = Highest Common Factor, GCD = Greatest Common Divisor. Both find the largest number that divides two or more numbers exactly.",
    status: "ANSWERED",
    createdAt: "2026-03-21T14:00:00",
    answeredAt: "2026-03-21T16:30:00",
  },
  {
    id: "dbt-004",
    studentId: "std-004",
    studentName: "Sneha Patel",
    studentInitials: "SP",
    studentColor: "#10B981",
    className: "Grade 7-A",
    teacherId: "tch-002",
    teacherName: "Mr. R. Sharma",
    subject: "Science",
    topic: "Photosynthesis",
    content:
      "Why do plants need sunlight? Can artificial light work?",
    answer:
      "Plants use sunlight for the energy needed to convert CO2 and water into glucose. Artificial light works if it provides the right wavelengths — that is how plants grow in greenhouses!",
    status: "ANSWERED",
    createdAt: "2026-03-21T09:00:00",
    answeredAt: "2026-03-21T11:00:00",
  },
];

export const TIMETABLE = {
  periods: [
    { no: 1, time: "8:00–8:45", isBreak: false },
    { no: 2, time: "8:45–9:30", isBreak: false },
    { no: 3, time: "9:30–10:15", isBreak: false },
    { no: "B", time: "10:15–10:30", isBreak: true, label: "Interval" },
    { no: 4, time: "10:30–11:15", isBreak: false },
    { no: 5, time: "11:15–12:00", isBreak: false },
    { no: 6, time: "12:00–12:45", isBreak: false },
    { no: "L", time: "12:45–1:30", isBreak: true, label: "Lunch" },
    { no: 7, time: "1:30–2:15", isBreak: false },
    { no: 8, time: "2:15–3:00", isBreak: false },
  ],
  slots: {
    "cls-005": [
      { period: 1, day: 1, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 1, day: 2, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 1, day: 3, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 1, day: 4, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 1, day: 5, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 1, day: 6, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 2, day: 1, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 2, day: 2, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 2, day: 3, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 2, day: 4, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 2, day: 5, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 2, day: 6, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 12" },
      { period: 3, day: 1, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 3, day: 2, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 12" },
      { period: 3, day: 3, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 3, day: 4, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 3, day: 5, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 3, day: 6, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 4, day: 1, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 4, day: 2, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 4, day: 3, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 4, day: 4, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 4, day: 5, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 4, day: 6, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 5, day: 1, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 12" },
      { period: 5, day: 2, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 5, day: 3, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 5, day: 4, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 5, day: 5, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 12" },
      { period: 5, day: 6, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 6, day: 1, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 6, day: 2, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 6, day: 3, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 6, day: 4, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 12" },
      { period: 6, day: 5, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 6, day: 6, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 7, day: 1, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 7, day: 2, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 7, day: 3, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 7, day: 4, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 7, day: 5, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 12" },
      { period: 7, day: 6, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 8, day: 1, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
      { period: 8, day: 2, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 8, day: 3, subject: "SST", teacher: "Mrs. S. Nair", color: "#EC4899", room: "Room 12" },
      { period: 8, day: 4, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 12" },
      { period: 8, day: 5, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 12" },
      { period: 8, day: 6, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 12" },
    ],
    "cls-003": [
      { period: 1, day: 1, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 1, day: 2, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 1, day: 3, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 8" },
      { period: 1, day: 4, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 1, day: 5, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 1, day: 6, subject: "SST", teacher: "Mr. R. Sharma", color: "#EC4899", room: "Room 8" },
      { period: 2, day: 1, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 2, day: 2, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 2, day: 3, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 2, day: 4, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 2, day: 5, subject: "SST", teacher: "Mr. R. Sharma", color: "#EC4899", room: "Room 8" },
      { period: 2, day: 6, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 3, day: 1, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 3, day: 2, subject: "SST", teacher: "Mr. R. Sharma", color: "#EC4899", room: "Room 8" },
      { period: 3, day: 3, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 3, day: 4, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 3, day: 5, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 8" },
      { period: 3, day: 6, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 4, day: 1, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 8" },
      { period: 4, day: 2, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 4, day: 3, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 4, day: 4, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 8" },
      { period: 4, day: 5, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 4, day: 6, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 5, day: 1, subject: "SST", teacher: "Mr. R. Sharma", color: "#EC4899", room: "Room 8" },
      { period: 5, day: 2, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 8" },
      { period: 5, day: 3, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 5, day: 4, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 5, day: 5, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 5, day: 6, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 8" },
      { period: 6, day: 1, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 6, day: 2, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 6, day: 3, subject: "SST", teacher: "Mr. R. Sharma", color: "#EC4899", room: "Room 8" },
      { period: 6, day: 4, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 6, day: 5, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 6, day: 6, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 7, day: 1, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 7, day: 2, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 7, day: 3, subject: "Hindi", teacher: "Mrs. P. Mehta", color: "#F59E0B", room: "Room 8" },
      { period: 7, day: 4, subject: "English", teacher: "Mrs. P. Mehta", color: "#8B5CF6", room: "Room 8" },
      { period: 7, day: 5, subject: "Free", teacher: "", color: "#E8EDF5", room: "" },
      { period: 7, day: 6, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 8, day: 1, subject: "SST", teacher: "Mr. R. Sharma", color: "#EC4899", room: "Room 8" },
      { period: 8, day: 2, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 8, day: 3, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
      { period: 8, day: 4, subject: "SST", teacher: "Mr. R. Sharma", color: "#EC4899", room: "Room 8" },
      { period: 8, day: 5, subject: "Science", teacher: "Mr. R. Sharma", color: "#10B981", room: "Room 8" },
      { period: 8, day: 6, subject: "Mathematics", teacher: "Mrs. S. Kumari", color: "#3B82F6", room: "Room 8" },
    ],
  } as Record<string, Array<{ period: number; day: number; subject: string; teacher: string; color: string; room: string }>>,
};

export const ATTENDANCE_RECORDS: Record<string, Record<string, Array<{
  studentId: string;
  name: string;
  initials: string;
  color: string;
  status: string;
  note: string;
}>>> = {
  "cls-005": {
    "2026-03-22": [
      { studentId: "std-001", name: "Priya Nair", initials: "PN", color: "#EC4899", status: "present", note: "" },
      { studentId: "std-002", name: "Rahul Mehta", initials: "RM", color: "#3B82F6", status: "present", note: "" },
      { studentId: "std-003", name: "Arjun Sharma", initials: "AS", color: "#FF6B35", status: "present", note: "" },
      { studentId: "std-005", name: "Dev Kumar", initials: "DK", color: "#8B5CF6", status: "absent", note: "Fever" },
      { studentId: "std-009", name: "Meena Iyer", initials: "MI", color: "#0EA5E9", status: "late", note: "Bus delayed" },
    ],
  },
  "cls-003": {
    "2026-03-22": [
      { studentId: "std-004", name: "Sneha Patel", initials: "SP", color: "#10B981", status: "present", note: "" },
      { studentId: "std-007", name: "Anita Singh", initials: "AN", color: "#EF4444", status: "absent", note: "Not informed" },
    ],
  },
};

export const ACTIVITY_FEED = [
  { id: "act-001", icon: "Swords", color: "#FF6B35", text: "Rahul won Tug of War vs Priya in Maths", time: "5m ago", link: "/school/students/std-002" },
  { id: "act-002", icon: "ClipboardList", color: "#3B82F6", text: "Mrs. Kumari assigned Microorganisms Quiz to 7-A", time: "12m ago", link: "/school/assignments/asgn-002" },
  { id: "act-003", icon: "CheckCircle", color: "#10B981", text: "23 students completed Integers Practice", time: "18m ago", link: "/school/assignments/asgn-002" },
  { id: "act-004", icon: "Star", color: "#FFB347", text: "Arjun earned Perfect 100 badge", time: "22m ago", link: "/school/students/std-003" },
  { id: "act-005", icon: "MessageCircle", color: "#8B5CF6", text: "Parent Mrs. Mehta messaged Mrs. Kumari", time: "28m ago", link: "/school/doubts" },
  { id: "act-006", icon: "Cpu", color: "#0EA5E9", text: "AI generated 3 quizzes for Grade 7 Science", time: "35m ago", link: "/school/assignments" },
];

export const CLASS_PERFORMANCE_TREND = [74, 76, 79, 78, 81, 82, 82, 83];
